--------------------
Failed to process https://github.com/startbootstrap/startbootstrap-grayscale.git repo
Traceback (most recent call last):
  File "/style-analyzer/lookout/style/format/benchmarks/quality_report.py", line 312, in generate_quality_report
    vnodes_expected_number=vnodes_expected_number)
  File "/style-analyzer/lookout/style/format/benchmarks/quality_report.py", line 135, in measure_quality
    (restarts, repository))
RuntimeError: Run out of 3 attempts. Failed to train proper model for https://github.com/startbootstrap/startbootstrap-grayscale.git.
--------------------
Failed to process https://github.com/sroze/nginfinitescroll.git repo
Traceback (most recent call last):
  File "/style-analyzer/lookout/style/format/benchmarks/quality_report.py", line 312, in generate_quality_report
    vnodes_expected_number=vnodes_expected_number)
  File "/style-analyzer/lookout/style/format/benchmarks/quality_report.py", line 135, in measure_quality
    (restarts, repository))
RuntimeError: Run out of 3 attempts. Failed to train proper model for https://github.com/sroze/nginfinitescroll.git.
--------------------
Failed to process https://github.com/vault-development/react-native-svg-uri.git repo
Traceback (most recent call last):
  File "/style-analyzer/lookout/style/format/benchmarks/quality_report.py", line 312, in generate_quality_report
    vnodes_expected_number=vnodes_expected_number)
  File "/style-analyzer/lookout/style/format/benchmarks/quality_report.py", line 135, in measure_quality
    (restarts, repository))
RuntimeError: Run out of 3 attempts. Failed to train proper model for https://github.com/vault-development/react-native-svg-uri.git.
--------------------
Failed to process https://github.com/processing/p5.js.git repo
Traceback (most recent call last):
  File "/style-analyzer/lookout/style/format/benchmarks/quality_report.py", line 312, in generate_quality_report
    vnodes_expected_number=vnodes_expected_number)
  File "/style-analyzer/lookout/style/format/benchmarks/quality_report.py", line 135, in measure_quality
    (restarts, repository))
RuntimeError: Run out of 3 attempts. Failed to train proper model for https://github.com/processing/p5.js.git.
